import { isGeneratedMediaPlaceholder } from '@/lib/media/media-ref';

/** Silent pixel used when a placeholder has no generated bytes yet. */
export const UNRESOLVED_HTML_MEDIA_SRC =
  'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';

const PARENT_BLOB_RE = /blob:[^\s"'<>)\\]+/gi;
const CSS_URL_RE = /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)"']+))\s*\)/gi;
const QUOTED_PLACEHOLDER_RE = /(['"`])((?:gen_(?:img|vid)|lesson_img)_[\w-]+)\1/gi;
const BLOCKS_RE =
  /<!--[\s\S]*?-->|<script\b[^>]*>[\s\S]*?<\/script\s*>|<style\b[^>]*>[\s\S]*?<\/style\s*>|<[a-zA-Z][a-zA-Z0-9:-]*\b(?:[^>"']|"[^"]*"|'[^']*')*>/gi;

export function isParentBlobUrl(url: string): boolean {
  return url.slice(0, 5).toLowerCase() === 'blob:';
}

/** Parent-created blob: URLs anywhere in the document, including CSS and scripts. */
export function parentBlobUrlsInHtml(html: string): string[] {
  return [...new Set(html.match(PARENT_BLOB_RE) ?? [])];
}

/**
 * Sandboxed srcDoc iframes omit allow-same-origin, so parent-created blob:
 * URLs fail to load. Inline them as data: URLs the unique-origin document can
 * render. https/data URLs pass through.
 */
export async function iframeSafeMediaUrl(url: string): Promise<string> {
  if (!isParentBlobUrl(url)) return url;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to read blob media (${response.status})`);
  const blob = await response.blob();
  const bytes = new Uint8Array(await blob.arrayBuffer());
  let binary = '';
  const chunk = 0x8000;
  for (let index = 0; index < bytes.length; index += chunk) {
    binary += String.fromCharCode(...bytes.subarray(index, Math.min(index + chunk, bytes.length)));
  }
  const mime = blob.type || 'application/octet-stream';
  return `data:${mime};base64,${btoa(binary)}`;
}

export interface HtmlMediaReference {
  readonly ref: string;
  readonly kind:
    | 'image-src'
    | 'video-src'
    | 'video-poster'
    | 'css-url'
    | 'css-attr-url'
    | 'script-ref';
  readonly start: number;
  readonly end: number;
  readonly owner: number;
}

function isCssMediaUrl(ref: string): boolean {
  return !/^(javascript|vbscript|about):/i.test(ref.trim());
}

function pushCssUrls(
  source: string,
  sourceIndex: number,
  owner: number,
  references: HtmlMediaReference[],
  kind: 'css-url' | 'css-attr-url',
): void {
  for (const match of source.matchAll(CSS_URL_RE)) {
    const ref = (match[1] ?? match[2] ?? match[3])?.trim();
    if (!ref || match.index === undefined || !isCssMediaUrl(ref)) continue;
    const prefix = /url\(\s*["']?/i.exec(match[0])![0];
    const start = sourceIndex + match.index + prefix.length;
    references.push({ ref, kind, start, end: start + ref.length, owner });
  }
}

function pushSrcPoster(
  tag: string,
  tagIndex: number,
  tagName: string,
  references: HtmlMediaReference[],
): void {
  const attributes = /\s([^\s=<>/]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g;
  for (const attribute of tag.matchAll(attributes)) {
    if (!/^(src|poster)$/i.test(attribute[1]) || attribute.index === undefined) continue;
    const ref = attribute[2] ?? attribute[3] ?? attribute[4];
    if (!ref) continue;
    const prefix = /^\s(?:src|poster)\s*=\s*["']?/i.exec(attribute[0])![0];
    const start = tagIndex + attribute.index + prefix.length;
    references.push({
      ref,
      kind:
        attribute[1].toLowerCase() === 'poster'
          ? 'video-poster'
          : tagName.toLowerCase() === 'img'
            ? 'image-src'
            : 'video-src',
      start,
      end: start + ref.length,
      owner: tagIndex,
    });
  }
}

function pushHref(tag: string, tagIndex: number, references: HtmlMediaReference[]): void {
  const attributes = /\s([^\s=<>/]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g;
  for (const attribute of tag.matchAll(attributes)) {
    if (!/^(?:xlink:)?href$/i.test(attribute[1]) || attribute.index === undefined) continue;
    const ref = attribute[2] ?? attribute[3] ?? attribute[4];
    if (!ref || ref.startsWith('#')) continue;
    const prefix = /^\s(?:xlink:)?href\s*=\s*["']?/i.exec(attribute[0])![0];
    const start = tagIndex + attribute.index + prefix.length;
    references.push({
      ref,
      kind: 'image-src',
      start,
      end: start + ref.length,
      owner: tagIndex,
    });
  }
}

function pushQuotedPlaceholders(
  source: string,
  sourceIndex: number,
  owner: number,
  references: HtmlMediaReference[],
): void {
  for (const match of source.matchAll(QUOTED_PLACEHOLDER_RE)) {
    const ref = match[2];
    if (!ref || match.index === undefined || !isGeneratedMediaPlaceholder(ref)) continue;
    const start = sourceIndex + match.index + match[1].length;
    references.push({
      ref,
      kind: 'script-ref',
      start,
      end: start + ref.length,
      owner,
    });
  }
}

function pushStyleAttributeUrls(
  tag: string,
  tagIndex: number,
  references: HtmlMediaReference[],
): void {
  const attribute = /\sstyle\s*=\s*(?:"([^"]*)"|'([^']*)')/i.exec(tag);
  if (!attribute || attribute.index === undefined) return;
  const value = attribute[1] ?? attribute[2] ?? '';
  const quote = /^\sstyle\s*=\s*["']/i.exec(attribute[0])![0];
  pushCssUrls(
    value,
    tagIndex + attribute.index + quote.length,
    tagIndex,
    references,
    'css-attr-url',
  );
}

/** Literal media attributes and CSS url() only: never rewrite prose or inline scripts. */
export function htmlMediaReferences(html: string): HtmlMediaReference[] {
  const references: HtmlMediaReference[] = [];
  for (const tag of html.matchAll(BLOCKS_RE)) {
    const raw = tag[0];
    const index = tag.index;
    if (index === undefined) continue;
    if (raw.startsWith('<!--')) continue;
    if (/^<script/i.test(raw)) {
      const open = raw.match(/^<script\b[^>]*>/i);
      if (open) {
        pushQuotedPlaceholders(
          raw.slice(open[0].length),
          index + open[0].length,
          index,
          references,
        );
      }
      continue;
    }
    if (/^<style/i.test(raw)) {
      const open = raw.match(/^<style\b[^>]*>/i);
      if (open) {
        pushCssUrls(
          raw.slice(open[0].length),
          index + open[0].length,
          index,
          references,
          'css-url',
        );
      }
      continue;
    }
    const name = /^<([a-zA-Z][a-zA-Z0-9:-]*)/.exec(raw)?.[1];
    if (name && /^(img|video|audio|source)$/i.test(name)) {
      pushSrcPoster(raw, index, name, references);
    }
    if (name && /^(image|use)$/i.test(name)) {
      pushHref(raw, index, references);
    }
    pushStyleAttributeUrls(raw, index, references);
  }
  return references;
}

function escapeHtmlAttributeValue(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('`', '&#96;')
    .replaceAll('=', '&#61;')
    .replace(/\s/g, (character) => `&#${character.charCodeAt(0)};`);
}

export function replaceHtmlMediaReferences(
  html: string,
  replacements: Readonly<Record<string, string>>,
): string {
  let result = html;
  for (const reference of htmlMediaReferences(html).reverse()) {
    if (!Object.hasOwn(replacements, reference.ref)) continue;
    // <style> text is rawtext: HTML entities are not decoded. Attribute
    // values still need quoting-safe escapes so unquoted src= cannot break out.
    const replacement =
      reference.kind === 'css-url' || reference.kind === 'script-ref'
        ? replacements[reference.ref]
        : escapeHtmlAttributeValue(replacements[reference.ref]);
    result = result.slice(0, reference.start) + replacement + result.slice(reference.end);
  }
  return result;
}
